### ISSUE TITLE
Limit the amount of terminals

### ISSUE THREAD

**Issue by petersutter** [gardener/terminal-controller-manager#16]
Limit the amount of terminal resources
- per user: default `15`
- per namespace: default `150`

This should be configurable.

**Comment by petersutter** [comment]
To limit the amount of terminals for a given namespace a resource quota can be created, e.g.

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: terminal-resource-quota
  namespace: my-namespace
spec:
  hard:
    count/terminals.dashboard.gardener.cloud: 20
```
